### ISSUE TITLE
basic pytorch question

### ISSUE THREAD

**Issue by AlJohri** [hpzhao/SummaRuNNer#9]
hi @hpzhao, I have a rather basic pytorch question that I'm having trouble googling. I'm working on converting the code to run on a CPU (at test time) and it was mostly easy enough. so far I had to add a `map_location` function to `torch.load` and put if statements around each use of cuda in `test.py`.

changes made so far:

```python
net = SummaRuNNer(config)
net = net.cuda() if args.gpu is not None else net.cpu()
if args.gpu is not None:
    net.load_state_dict(torch.load(args.model_file))
else:
    net.load_state_dict(torch.load(args.model_file, map_location=lambda storage, loc: storage))
```

```python
sents = Variable(torch.from_numpy(x))
if args.gpu is not None:
    sents = sents.cuda() 
```

--------------------------

the part that I can't quite understand is why the `Variable` has a `.cuda()` at the end of it within the model.py?
- `s = Variable(torch.zeros(100, 1)).cuda()`
- `position_index = Variable(torch.LongTensor([[position]])).cuda()`

Can you explain what adding `.cuda()` to the end of the Variable does here? I thought that this is enough on the outside:

```
net = SummaRuNNer(config)
net.cuda()
```

thanks!

-- super novice pytorch user

**Comment by hpzhao** [comment]
net.cuda() only process the Parameters in net . So I add .cuda in temp Variable. The code is just a. sample . huaipengzhao 邮箱：huaipengzhao@gmail.com 签名由 网易邮箱大师 定制 在2018年02月02日 12:11，Al Johri 写道： hi @hpzhao, I have a rather basic pytorch question that I'm having trouble googling. I'm working on converting the code to run on a CPU (at test time) and it was mostly easy enough one part that I can't quite understand is why the Variable has a .cuda() at the end of it within the model? s = Variable(torch.zeros(100, 1)).cuda() and position_index = Variable(torch.LongTensor([[position]])).cuda() Usually most models I see don't explicitly say this in the model class itself allowing the model to easily run on both the gpu and cpu. I also don't think it makes sense to change the config of the model to pass in gpu/device. Can you explain what adding .cuda() to the end of the Variable does here? I thought that this is enough on the outside: net = SummaRuNNer(config)
net.cuda()
 thanks! super novice pytorch user — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by AlJohri** [comment]
thanks @hpzhao, this helps a bit
